import type { z } from 'zod'
import type { BrowserConfigSchema } from '@/engine/content-schema'

/**
 * A closed 2009 internet. No page here reaches the real network, and the index only knows what
 * exists inside this simulation. Pages carry `variants` keyed on temporal shift — the same URL
 * resolves to different text once the player has moved the timeline far enough.
 */
export const browser: z.input<typeof BrowserConfigSchema> = {
  home: 'corvid.com',
  engineName: 'CORVID',
  emptyResults:
    'Your search did not match any documents.\nTry different keywords. Remember: this index only knows what exists now.',
  pages: [
    {
      url: 'tradepost.com/pdx/electronics',
      background: '#fff',
      dark: false,
      blocks: [
        { kind: 'heading', text: 'TradePost — Portland / electronics', ink: '#7a0f0f' },
        { kind: 'sub', text: 'posted today · 4 items · flag as spam' },
        { kind: 'rule' },
        {
          kind: 'listing',
          title: 'Nokora N90 — unlocked, boxed',
          price: '$60',
          location: 'SE Portland · cash only',
          text: 'Company gave it to my brother, he never used it. No idea what it is worth. Screen is like a little computer. Comes with the charger and a paper manual.',
          action: 'buy',
          itemId: 'tradepost-n90',
        },
        {
          kind: 'listing',
          title: 'Sony CRT television 27"',
          price: '$25',
          location: 'Gresham · you haul',
          text: 'Works. Heavy. Bring two people and a truck.',
          action: 'none',
          itemId: null,
        },
        {
          kind: 'listing',
          title: 'Snowboard, 158cm',
          price: '$140',
          location: 'Hillsboro',
          text: 'Ridden two seasons. Bindings included.',
          action: 'none',
          itemId: null,
        },
      ],
      variants: [],
    },
    {
      url: 'columbia-register.com/obits/rask',
      background: '#fbfbf5',
      dark: false,
      blocks: [
        { kind: 'heading', text: 'Obituaries — December 2008', ink: '#1a1a1a' },
        { kind: 'sub', text: 'The Columbia Register · archived page' },
        { kind: 'rule' },
        {
          kind: 'p',
          text: 'RASK, Owen T., 34, of Portland, died Friday, December 19, 2008, following a short illness. He was a systems technician. He is survived by no immediate family. At his request there will be no service.',
        },
        { kind: 'p', text: 'Condolences may be left in the guest book below. (Guest book is empty.)' },
        { kind: 'evidence', evidenceId: 'e3' },
      ],
      variants: [],
    },
    {
      url: 'aion-group.com',
      background: '#f2f2ee',
      dark: false,
      blocks: [
        { kind: 'heading', text: 'AION GROUP', ink: '#22262b' },
        { kind: 'sub', text: 'Settlements · Recovery · Actuarial' },
        { kind: 'rule' },
        { kind: 'p', text: 'This domain is registered and in use. No public information is available.' },
        { kind: 'p', text: 'Correspondence is outbound only.' },
      ],
      variants: [],
    },
    {
      url: 'nullcache.org/thread/3312',
      background: '#0f1216',
      dark: true,
      blocks: [
        { kind: 'heading', text: 'nullcache › general › “anyone else lose a week?”', ink: '#8fb6d4' },
        { kind: 'sub', text: '12 replies · last post 09 Jan 2009' },
        { kind: 'rule' },
        {
          kind: 'p',
          text: '>> 3312  anon\nwoke up tuesday and it was tuesday but the whole apartment was someone elses. bank card in a name thats not mine and it works. am i insane',
        },
        {
          kind: 'p',
          text: '>> 3319  anon\nhappened to a guy on here in november. he stopped posting. dont use your real name and dont pay them',
        },
        { kind: 'p', text: '>> 3327  anon\nthirty days is the number they always give. thats all i will say' },
      ],
      variants: [],
    },
    {
      url: 'cluster.com/leavoss',
      background: '#eef2f6',
      dark: false,
      blocks: [
        { kind: 'heading', text: 'Cluster — lea.voss', ink: '#2b5f96' },
        { kind: 'sub', text: 'Portland, OR · 41 friends · last updated today, 04:12' },
        { kind: 'rule' },
        {
          kind: 'p',
          text: '04:12 — someone has been parked outside my building for two nights. same car. i am writing this here so it is written somewhere.',
        },
        { kind: 'p', text: '11 Jan — demo works in three browsers. it does not work in the one everybody uses.' },
        { kind: 'p', text: '02 Jan — new year, same four months of runway.' },
        { kind: 'evidence', evidenceId: 'e9' },
      ],
      variants: [],
    },
    {
      url: 'namewell.com/register',
      background: '#fdfdf8',
      dark: false,
      blocks: [
        { kind: 'heading', text: 'NAMEWELL — domain registration', ink: '#1f4e79' },
        { kind: 'sub', text: '$9.95 per year · instant activation · WHOIS lookup below' },
        { kind: 'rule' },
        {
          kind: 'listing',
          title: 'shortclip.com',
          price: '$9.95',
          location: 'available',
          text: 'Four syllables, no hyphen. Nobody has asked about this one.',
          action: 'domain',
          itemId: 'shortclip.com',
        },
        {
          kind: 'listing',
          title: 'cloudrent.com',
          price: '$9.95',
          location: 'available',
          text: 'Renting computers by the hour. The listing has sat here since 2006.',
          action: 'domain',
          itemId: 'cloudrent.com',
        },
        {
          kind: 'listing',
          title: 'socialgraph.net',
          price: '$9.95',
          location: 'available',
          text: 'You have heard this phrase before. You cannot remember from where.',
          action: 'domain',
          itemId: 'socialgraph.net',
        },
        { kind: 'rule' },
        { kind: 'heading', text: 'WHOIS: aion-group.com', ink: '#22262b' },
        {
          kind: 'p',
          text: 'Registered: 11 Dec 2008\nRegistrant: AION GROUP LLC\nAddress: 1140 SE MORRISON ST, PORTLAND OR\nNameservers: ns1.aion-group.com, ns2.aion-group.com',
        },
        { kind: 'evidence', evidenceId: 'e10' },
      ],
      variants: [],
    },
    {
      url: 'columbia-register.com/business',
      background: '#fbfbf5',
      dark: false,
      blocks: [
        {
          kind: 'heading',
          text: 'Portland developer to demo plugin-free video at Ace Hotel',
          ink: '#1a1a1a',
        },
        { kind: 'sub', text: 'The Columbia Register · Business · 15 January 2009' },
        { kind: 'rule' },
        {
          kind: 'p',
          text: 'A developer working out of an apartment in Southeast Portland says she has built a way to play short video clips in a web page without additional software. Industry observers were skeptical, noting that few users have expressed interest in watching video in a browser window.',
        },
        { kind: 'p', text: 'Business · Markets · Real Estate · Classifieds' },
      ],
      variants: [
        {
          minShift: 2,
          blocks: [
            {
              kind: 'heading',
              text: 'Local video startup folds before demo; founder unreachable',
              ink: '#1a1a1a',
            },
            { kind: 'sub', text: 'The Columbia Register · Business · corrected 3 hours ago' },
            { kind: 'rule' },
            {
              kind: 'p',
              text: 'A local software project that had been scheduled to demonstrate in-browser video this month has been withdrawn. The developer did not respond to messages. An earlier version of this article named a different company and described a different outcome. We regret the error.',
            },
            { kind: 'p', text: 'You have read this page before. It did not say this.' },
          ],
        },
      ],
    },
  ],
  index: [
    {
      id: 'idx-tradepost',
      keys: ['phone', 'nokora', 'sell', 'flip', 'tradepost', 'classified', 'cash', 'money'],
      title: 'TradePost — Portland classifieds — electronics',
      url: 'tradepost.com/pdx/electronics',
      snippet: 'Free classified ads for the Portland metro area. Electronics posted today. Cash only, meet in public.',
      go: 'tradepost.com/pdx/electronics',
      variants: [],
    },
    {
      id: 'idx-obit',
      keys: ['owen rask', 'rask', 'o. rask', 'who am i', 'my name', 'obituary', 'owen'],
      title: 'Obituaries — December 2008 — The Columbia Register',
      url: 'columbia-register.com/obits/rask',
      snippet: 'RASK, Owen T., 34, of Portland, died Friday, December 19, 2008, following a short illness…',
      go: 'columbia-register.com/obits/rask',
      variants: [],
    },
    {
      id: 'idx-aion',
      keys: ['aion', 'aion group', 'quota', 'settlement'],
      title: 'AION GROUP',
      url: 'aion-group.com',
      snippet: 'Settlements · Recovery · Actuarial. No public information is available.',
      go: 'aion-group.com',
      variants: [],
    },
    {
      id: 'idx-nullcache',
      keys: ['thirty days', '30 days', 'woke up', 'lost week', 'time travel', 'not my apartment'],
      title: 'nullcache › “anyone else lose a week?”',
      url: 'nullcache.org/thread/3312',
      snippet: 'woke up tuesday and it was tuesday but the whole apartment was someone elses…',
      go: 'nullcache.org/thread/3312',
      variants: [],
    },
    {
      id: 'idx-btc',
      keys: ['bitcoin', 'btc'],
      title: 'P2P e-cash — mailing list archive',
      url: 'metzdowd.archive/crypto/2009-01',
      snippet: 'Announcing the first release of a new electronic cash system that uses a peer-to-peer network…',
      go: null,
      variants: [],
    },
    {
      id: 'idx-lea',
      keys: ['lea', 'voss', 'lea voss', 'cluster', 'video', 'startup'],
      title: 'Cluster — lea.voss',
      url: 'cluster.com/leavoss',
      snippet: 'someone has been parked outside my building for two nights. same car…',
      go: 'cluster.com/leavoss',
      variants: [],
    },
    {
      id: 'idx-namewell',
      keys: ['domain', 'domains', 'register', 'whois', 'namewell', 'buy a name'],
      title: 'NAMEWELL — domain registration · $9.95/yr',
      url: 'namewell.com/register',
      snippet: 'Instant activation. WHOIS lookup. Transfer in from any registrar.',
      go: 'namewell.com/register',
      variants: [],
    },
    {
      id: 'idx-business',
      keys: ['news', 'business', 'portland', 'headline', 'register', 'demo'],
      title: 'Portland developer to demo plugin-free video — The Columbia Register',
      url: 'columbia-register.com/business',
      snippet: 'A developer working out of an apartment in Southeast Portland says she has built…',
      go: 'columbia-register.com/business',
      variants: [
        {
          minShift: 2,
          title: 'Local video startup folds before demo — The Columbia Register',
          snippet: 'A local software project scheduled to demonstrate this month has been withdrawn…',
        },
      ],
    },
  ],
}
