import type { z } from 'zod'
import type { FileDocSchema } from '@/engine/content-schema'

type FileInput = z.input<typeof FileDocSchema>

export const files: FileInput[] = [
  {
    id: 'readme',
    icon: 'document',
    name: 'READ_ME.txt',
    meta: '1 KB',
    metaWhenDecrypted: null,
    body: [
      'QUOTA 01',
      '',
      'Amount due: $10,000.00',
      'Term: 30 calendar days',
      'Day: 01 of 30',
      '',
      'You will remember things that have not happened. This is not a symptom. It is the only asset you have.',
      '',
      'Do not contact anyone about this file.',
      'Do not attempt to leave the city.',
      'Do not use the name on the account for anything you would not want traced.',
      '',
      'Before the day ends:',
      '  Answer Deleon. He will offer you work. Take it or do not.',
      '  Find out what you still remember. It costs you to look.',
      '  Turn the balance into more than the balance.',
      '  Write down one thing you can prove.',
      '',
      'The balance is $437.82. Begin.',
    ].join('\n'),
    bodyWhenDecrypted: null,
    evidenceId: 'e1',
    evidenceRequiresDecryption: false,
    beat: 'readme',
  },
  {
    id: 'contacts',
    icon: 'document',
    name: 'contacts.txt',
    meta: '—',
    metaWhenDecrypted: null,
    body: [
      'deleon, marc     503-555-0148',
      'voss, lea        503-555-0072',
      'M                (no number)',
      'meridian s&l     1-800-555-9910',
    ].join('\n'),
    bodyWhenDecrypted: null,
    evidenceId: null,
    evidenceRequiresDecryption: false,
    beat: null,
  },
  {
    id: 'enc',
    icon: 'encrypted',
    name: 'cibles.enc',
    meta: 'locked',
    metaWhenDecrypted: 'decrypted',
    body: [
      '‹ binary ›',
      '',
      '1f 8b 08 00 4d 61 72 63 00 03 ed 5d 6b 73 db 46',
      '96 fd de 5f 41 c5 76 65 3b 8e 25 3f 92 65 4b 96',
      '…',
      '',
      'This file is encrypted. Terminal:  decrypt cibles.enc --key ????',
    ].join('\n'),
    bodyWhenDecrypted: [
      'cibles.enc — decrypted',
      '',
      'SUBJECT LIST (partial)',
      '----------------------------------',
      'MORAN, J.     status: CLOSED    12/2008',
      'OKONKWO, A.   status: CLOSED    12/2008',
      'RASK, O.      status: ACTIVE    01/2009',
      'VOSS, L.      status: WATCH     01/2009',
      '----------------------------------',
      'copied 14/01/2009 22:14 from host “deleon-pc”',
    ].join('\n'),
    evidenceId: 'e7',
    evidenceRequiresDecryption: true,
    beat: null,
  },
  {
    id: 'pics',
    icon: 'folder',
    name: 'Pictures',
    meta: 'folder',
    metaWhenDecrypted: null,
    body: 'Empty.',
    bodyWhenDecrypted: null,
    evidenceId: null,
    evidenceRequiresDecryption: false,
    beat: null,
  },
]
