import type { z } from 'zod'
import type { FileDocSchema } from '@/engine/content-schema'

type FileInput = z.input<typeof FileDocSchema>

/**
 * `files[0]` is the document the machine is showing when the player arrives. Opening it is what
 * fires the `brief` beat, and the night event does not fire beats — a file being on screen is not
 * the same as a file having been read, and the gate is about the second one.
 */
export const files: FileInput[] = [
  {
    id: 'brief',
    icon: 'document',
    name: 'QUOTA_02.txt',
    meta: '1 KB · modified 04:11',
    metaWhenDecrypted: null,
    body: [
      'QUOTA 02',
      '',
      'Amount due: $10,000.00',
      'Received to date: $0.00',
      'Day: 02 of 30',
      '',
      'You slept until 09:47. You did not set an alarm and nobody woke you, and four of the hours',
      'you were given are already spent. That will not be corrected tomorrow.',
      '',
      'Housekeeping from this end:',
      '  The console was used at 04:03 and released at 04:19, under your login. You were asleep.',
      '  Your bookmarks have been tidied. Nothing was removed.',
      '  The external volume from Wednesday night is still mounted. It was never yours.',
      '',
      'Before the day ends:',
      '  Answer Voss. She wrote to you first, which is a thing you should notice.',
      '  Find out who else has a hand on the account. It will not be in your mail.',
      '  Move the balance. Up is preferred. Moved is required.',
      '  Put one thing on record that will still be true on Monday.',
      '',
      'Do not go to the Morrison branch in person.',
      'Do not write to Deleon again. He will not read it and somebody else will.',
      '',
      'The day ends at 21:40. Begin.',
    ].join('\n'),
    bodyWhenDecrypted: null,
    evidenceId: null,
    evidenceRequiresDecryption: false,
    beat: 'brief',
  },
  {
    id: 'card',
    icon: 'image',
    name: 'signature_card.tif',
    meta: '1240 x 900 · greyscale · received 04:02',
    metaWhenDecrypted: null,
    body: [
      '[greyscale scan, 1240 x 900, no colour profile]',
      '',
      'MERIDIAN SAVINGS & LOAN — SPECIMEN SIGNATURE CARD',
      'ACCOUNT      ····4471          BRANCH  1140 SE MORRISON',
      'OPENED       06 JAN 2009       TELLER  3071',
      '------------------------------------------------------',
      'SPECIMEN 1   Owen T. Rask',
      '             taken 06 JAN 2009, 09:02',
      '',
      'SPECIMEN 2   [initials only, two characters, ink]',
      '             taken 14 JAN 2009, 16:40',
      '             AUTHORISED SECOND SIGNATORY — SEE FILE',
      '------------------------------------------------------',
      'CARD MUST NOT LEAVE THE BRANCH',
      '',
      'The scan is slightly out of square. Whoever made it photographed the card on a desk',
      'rather than putting it through a feeder, and a thumb is in the bottom left corner.',
    ].join('\n'),
    bodyWhenDecrypted: null,
    evidenceId: 'e1',
    evidenceRequiresDecryption: false,
    beat: null,
  },
  {
    id: 'route',
    icon: 'encrypted',
    name: 'route.enc',
    meta: 'locked',
    metaWhenDecrypted: 'decrypted',
    body: [
      '‹ binary ›',
      '',
      '1f 8b 08 00 52 4f 55 54 00 03 c5 5c 6b 6f db 46',
      '16 fd 2b 0a 8b 05 92 c0 96 44 52 8f 46 6d 51 c0',
      '…',
      '',
      'This file is encrypted. Terminal:  decrypt route.enc --key ????',
      '',
      'Four digits. It is the number of whoever stood behind the counter.',
    ].join('\n'),
    bodyWhenDecrypted: [
      'route.enc — decrypted',
      '',
      'COLLECTION ROUTE — FRI 16/01/2009 — VEHICLE 2',
      '----------------------------------------------------',
      '06:40   1822 SE 39TH AVE           COLLECT',
      '07:15   4110 SE HAWTHORNE BLVD     SERVE',
      '09:15   1140 SE MORRISON ST        DELIVER — HAND TO 3071 ONLY',
      '13:20   (address withheld — SALEM)  OBSERVE',
      '17:00   RETURN                     VEHICLE 2 OFF ROAD 17:00',
      '----------------------------------------------------',
      'ROUTE PREPARED 15/01/2009 23:52',
      'NOTE: 06:40 IS A COLLECT NOT A SERVE. DO NOT LEAVE PAPER.',
    ].join('\n'),
    evidenceId: 'e7',
    evidenceRequiresDecryption: true,
    beat: null,
  },
  {
    id: 'contacts',
    icon: 'document',
    name: 'contacts.txt',
    meta: 'modified 04:11',
    metaWhenDecrypted: null,
    body: [
      'deleon, marc     503-555-0148   1822 se 39th ave     (line disconnected 15/01)',
      'voss, lea        503-555-0072',
      'M                (no number)',
      'meridian s&l     1-800-555-9910',
      'morrison branch  503-555-0114   (recorded message, no option to hold)',
      'new accounts     3071           (do not call from this line)',
      '',
      '# the last two lines were not here yesterday',
    ].join('\n'),
    bodyWhenDecrypted: null,
    evidenceId: null,
    evidenceRequiresDecryption: false,
    beat: null,
  },
  {
    id: 'pics',
    icon: 'folder',
    name: 'Pictures',
    meta: 'folder · modified 04:03',
    metaWhenDecrypted: null,
    body: 'Empty. Modified 16/01/2009 04:03.',
    bodyWhenDecrypted: null,
    evidenceId: null,
    evidenceRequiresDecryption: false,
    beat: null,
  },
]
