import type { z } from 'zod'
import type { WorldArtifactSchema } from '@/engine/world/schema'

type ArtifactInput = z.input<typeof WorldArtifactSchema>

/**
 * The traces. One fact, many surfaces.
 *
 * Most of what is here carries no fact at all, and that is the point: it is the rest of the
 * internet — a band on hiatus, a cycling club, a car park's opening hours. A world where every
 * page is about the case stops being a world.
 *
 * Every page on the web needs an address, and no two documents may share one. The case's own
 * pages are projected into this same graph by `content/index.ts`, so nothing here may sit at an
 * address a case already authored.
 */
export const artifacts: ArtifactInput[] = [
  // --------------------------------------------------------------- the case
  {
    id: 'w.registry-marlow-2013',
    type: 'record',
    date: '2014-02-11',
    title: 'Marlow Foundation — 2013 annual filing (scanned)',
    body: 'Directors of record for the year ended 31 December 2013: A. Marlow (Chair), J. Reyes (Treasurer), R. Vale (Director). Resignation of R. Vale recorded 14 March 2014.',
    source: 'Oregon Secretary of State — Corporation Division',
    surface: 'archive',
    url: 'sos.oregon.gov/nonprofits/marlow-2013',
    mentions: ['org.marlow-foundation', 'person.richard-vale', 'person.joel-reyes'],
    fields: { filed: '11 February 2014', pages: '6' },
    factId: 'fact.vale-marlow-2013',
  },
  {
    id: 'w.marlow-report-2013',
    type: 'webPage',
    date: '2014-05-02',
    title: 'The Marlow Foundation — 2013 in review',
    body: 'Our thanks to the board for a year of growth: Alice Marlow, Joel Reyes and Richard Vale. The Foundation disbursed grants across housing and arts programmes in five counties.',
    source: 'marlowfoundation.org/reports/2013',
    surface: 'web',
    url: 'marlowfoundation.org/reports/2013',
    mentions: ['org.marlow-foundation', 'person.richard-vale', 'person.joel-reyes'],
    factId: 'fact.vale-marlow-2013',
  },
  {
    id: 'w.ridgeline-about',
    type: 'webPage',
    date: '2025-11-04',
    title: 'Ridgeline Partners — About',
    body: 'Ridgeline was founded in Portland in 2011 by Richard Vale and two partners. We manage capital for families and foundations in the Pacific Northwest.',
    source: 'ridgelinepartners.com/about',
    surface: 'web',
    url: 'ridgelinepartners.com/about',
    mentions: ['org.ridgeline', 'person.richard-vale'],
    factId: 'fact.ridgeline-founded',
  },
  {
    id: 'w.business-journal-2011',
    type: 'webPage',
    date: '2011-09-19',
    title: 'Three leave Cascadia Capital to start Ridgeline',
    body: 'Richard Vale, formerly of Cascadia Capital, has registered a new advisory firm in Portland with two colleagues. Ridgeline Partners begins trading in October.',
    source: 'pdxbusinessjournal.com/2011/ridgeline-launch',
    surface: 'web',
    url: 'pdxbusinessjournal.com/2011/ridgeline-launch',
    mentions: ['person.richard-vale', 'org.ridgeline'],
    factId: 'fact.ridgeline-founded',
  },

  // ------------------------------------------------------------- the ordinary
  {
    id: 'w.fremont-faq',
    type: 'webPage',
    date: '2026-03-02',
    title: 'Fremont Street Parking — Frequently asked questions',
    body: 'How long do you keep camera footage? The barrier cameras write to an eleven-day loop. After that it is overwritten and we cannot recover it. Please contact us promptly.',
    source: 'fremontparking.com/faq',
    surface: 'web',
    url: 'fremontparking.com/faq',
    mentions: ['place.fremont-lot'],
    factId: 'fact.fremont-loop',
  },
  {
    id: 'w.alberta-thread-8812',
    type: 'forumPost',
    date: '2026-04-18',
    title: 'Anyone got footage from the Fremont lot?',
    body: 'Somebody clipped my mirror on level 2. Called the office and they said eleven days and then it is gone. Eleven days! Anyway if you saw a silver estate, you know where I am.',
    source: 'nextdoor-alberta.com/thread/8812',
    surface: 'web',
    url: 'nextdoor-alberta.com/thread/8812',
    mentions: ['place.fremont-lot'],
    factId: 'fact.fremont-loop',
  },
  {
    id: 'w.strava-club',
    type: 'webPage',
    date: '2026-05-05',
    title: 'Tuesday Night Hill Club — members',
    body: 'Rides leave from the east end of the Tilikum at 18:30, all weathers. Current members include N. Okafor, P. Brandt, S. Ellery and eleven others.',
    source: 'tuesdayhillclub.org/members',
    surface: 'web',
    url: 'tuesdayhillclub.org/members',
    mentions: ['person.nadia-okafor'],
    factId: 'fact.nadia-cycles',
  },
  {
    id: 'w.bike-classified',
    type: 'classified',
    date: '2026-05-21',
    title: 'Steel road bike, 54cm — $640',
    body: 'Selling my winter bike, 54cm steel frame, recently serviced. Collection in Sellwood, evenings. I ride Tuesdays so message rather than call.',
    source: 'pdxclassifieds.com/bikes/54cm-steel',
    surface: 'web',
    url: 'pdxclassifieds.com/bikes/54cm-steel',
    mentions: ['person.nadia-okafor'],
    factId: 'fact.nadia-cycles',
  },
  {
    id: 'w.dougfir-listing',
    type: 'webPage',
    date: '2026-05-30',
    title: 'Doug Fir Lounge — 30 May: The Hollow Coast',
    body: 'The Hollow Coast, with support from Weather Systems. Doors 20:00. This is being billed as their last show for a while.',
    source: 'dougfirlounge.com/shows/2026-05-30',
    surface: 'web',
    url: 'dougfirlounge.com/shows/2026-05-30',
    mentions: ['org.hollow-coast'],
    factId: 'fact.hollow-coast-hiatus',
  },
  {
    id: 'w.hollow-coast-press',
    type: 'webPage',
    date: '2026-06-01',
    title: 'The Hollow Coast — press',
    body: 'After six years we are taking the rest of the year off. Thank you to everyone who came to the Doug Fir. The van is for sale and so is the second-best amp.',
    source: 'pdxbands.com/the-hollow-coast/press',
    surface: 'web',
    url: 'pdxbands.com/the-hollow-coast/press',
    mentions: ['org.hollow-coast'],
    factId: 'fact.hollow-coast-hiatus',
  },
  {
    id: 'w.vernon-staff',
    type: 'webPage',
    date: '2025-09-08',
    title: 'Vernon Elementary — Fourth grade',
    body: 'Room 12 — Ms C. Mercer. Room 14 — Mr D. Achterberg. Fourth grade families, please use the Alberta Street entrance after 08:15.',
    source: 'vernon-elementary.pps.net/staff/grade-4',
    surface: 'web',
    url: 'vernon-elementary.pps.net/staff/grade-4',
    mentions: ['person.claire-mercer'],
    factId: 'fact.claire-teaches',
  },
  {
    id: 'w.vernon-newsletter',
    type: 'webPage',
    date: '2026-05-15',
    title: 'Vernon Elementary — May newsletter',
    body: 'Thank you to Ms Mercer for organising the fourth-grade trip to the Columbia Gorge, and to the eleven parents who drove.',
    source: 'vernon-elementary.pps.net/news/may-2026',
    surface: 'web',
    url: 'vernon-elementary.pps.net/news/may-2026',
    mentions: ['person.claire-mercer'],
    factId: 'fact.claire-teaches',
  },

  // A sincerely wrong document, and the thing that catches it. A lie the player cannot catch is
  // not a lie — it is the world simply telling them something untrue.
  {
    id: 'w.neighbour-sighting',
    type: 'forumPost',
    date: '2026-06-12',
    title: 'Re: missing man on Alberta',
    body: 'I am fairly sure I saw him on the Wednesday morning by the coffee place, so whatever the family says he was still around on the 10th.',
    source: 'nextdoor-alberta.com/thread/9004',
    surface: 'web',
    url: 'nextdoor-alberta.com/thread/9004',
    mentions: ['person.daniel-mercer', 'place.alberta'],
    reliability: 'mistaken',
    disputedClaim: 'he was still around on the 10th',
    contradicts: ['w.coffee-closure'],
  },
  {
    id: 'w.coffee-closure',
    type: 'webPage',
    date: '2026-06-08',
    title: 'Proud Mary Alberta — closed 10–14 June',
    body: 'We are closed Wednesday the 10th through Sunday the 14th for a floor replacement. The Division shop is open as usual. Sorry for the inconvenience.',
    source: 'proudmarycafe.com/notices/june-closure',
    surface: 'web',
    url: 'proudmarycafe.com/notices/june-closure',
    mentions: ['place.alberta'],
  },

  // -------------------------------------------------------- ordinary, no fact
  {
    id: 'w.alberta-block-party',
    type: 'webPage',
    date: '2026-06-02',
    title: 'Alberta Street block party — 4 July',
    body: 'Volunteers still needed for setup, the lemonade table and the 17:00 teardown. Street closure runs from 21st to 26th.',
    source: 'albertamainst.org/block-party-2026',
    surface: 'web',
    url: 'albertamainst.org/block-party-2026',
    mentions: ['place.alberta', 'org.alberta-main-street'],
    factId: 'fact.alberta-closure',
  },
  {
    id: 'w.lost-cat',
    type: 'classified',
    date: '2026-06-11',
    title: 'Lost: grey tabby, NE 22nd and Alberta',
    body: 'Answers to Pilot, or does not. Chipped. He has been out four nights and I am not sleeping. Any sighting, any time.',
    source: 'pdxclassifieds.com/lost/pilot-grey-tabby',
    surface: 'web',
    url: 'pdxclassifieds.com/lost/pilot-grey-tabby',
    mentions: ['place.alberta', 'person.marguerite-hoy'],
    factId: 'fact.pilot-comes-home',
  },
  {
    id: 'w.kiln-sale',
    type: 'classified',
    date: '2026-05-27',
    title: 'Electric kiln, Skutt KM-1027 — $1,900',
    body: 'Studio closing after eleven years. Kiln, two wheels, and about forty bats. Buyer collects, and you will need three people and a van.',
    source: 'pdxclassifieds.com/studio/skutt-km1027',
    surface: 'web',
    url: 'pdxclassifieds.com/studio/skutt-km1027',
    mentions: ['person.sofia-ellery', 'place.division-studio'],
    factId: 'fact.kiln-sold',
  },
  {
    id: 'w.bridge-closure',
    type: 'webPage',
    date: '2026-06-05',
    title: 'Fremont Bridge — overnight lane closures',
    body: 'Northbound lanes close 22:00 to 05:00 from 8 June to 19 June for deck inspection. Use the Broadway Bridge.',
    source: 'portlandoregon.gov/transport/fremont-june',
    surface: 'web',
    url: 'portlandoregon.gov/transport/fremont-june',
    mentions: [],
  },
  {
    id: 'w.kgw-weather',
    type: 'webPage',
    date: '2026-06-09',
    title: 'Portland forecast — Tuesday 9 June',
    body: 'Cloud clearing after 21:00, low of 11. Dry through midweek. Rain returns Thursday evening.',
    source: 'kgw-portland.com/weather/2026-06-09',
    surface: 'web',
    url: 'kgw-portland.com/weather/2026-06-09',
    mentions: ['org.kgw'],
  },
  {
    id: 'w.whitfield-byline',
    type: 'webPage',
    date: '2026-06-14',
    title: 'Amara Whitfield — recent stories',
    body: 'Housing bond shortfall · County shelter contract · School board resignation · Family appeals for information on missing Portland man.',
    source: 'kgw-portland.com/staff/amara-whitfield',
    surface: 'web',
    url: 'kgw-portland.com/staff/amara-whitfield',
    mentions: ['person.amara-whitfield', 'org.kgw'],
  },
  {
    id: 'w.ridgeline-hiring',
    type: 'webPage',
    date: '2026-04-30',
    title: 'Ridgeline Partners — Careers',
    body: 'We are hiring an operations associate. Portland office, four days on site. No agencies.',
    source: 'ridgelinepartners.com/careers',
    surface: 'web',
    url: 'ridgelinepartners.com/careers',
    mentions: ['org.ridgeline'],
  },
  {
    id: 'w.marlow-grants-2025',
    type: 'webPage',
    date: '2026-01-22',
    title: 'The Marlow Foundation — 2025 grants',
    body: 'Forty-one grants across housing, arts and early education. The Foundation does not accept unsolicited applications.',
    source: 'marlowfoundation.org/grants/2025',
    surface: 'web',
    url: 'marlowfoundation.org/grants/2025',
    mentions: ['org.marlow-foundation'],
  },
  {
    id: 'w.storage-unit',
    type: 'webPage',
    date: '2026-02-14',
    title: 'Rose City Self Storage — access hours',
    body: 'Gate access 06:00 to 22:00 daily. Units are accessed by a four-digit code set by the tenant. Codes are not held by staff.',
    source: 'rosecitystorage.com/access',
    surface: 'web',
    url: 'rosecitystorage.com/access',
    mentions: [],
  },
  {
    id: 'w.cascade-mobile-coverage',
    type: 'webPage',
    date: '2026-03-19',
    title: 'Cascade Mobile — coverage and records',
    body: 'Call and message metadata is retained for 90 days on your account and for longer under our carrier obligations. Handsets hold the last 30 days.',
    source: 'cascademobile.com/support/records',
    surface: 'web',
    url: 'cascademobile.com/support/records',
    mentions: ['device.nova-m12'],
  },
  // ------------------------------------------------- the case, further traces

  /*
   * A plot fact needs four to six traces so that any two or three of them are enough, and the
   * rest are why the world feels larger than the case. Two players should be able to arrive at
   * the same conclusion from different halves of this.
   */
  {
    id: 'w.marlow-newsletter-2014',
    type: 'webPage',
    date: '2014-04-08',
    title: 'The Marlow Foundation — spring 2014 newsletter',
    body: 'With thanks to Richard Vale, who steps down from the board this spring after a period of considerable growth for the Foundation, and with best wishes for his work at Ridgeline.',
    source: 'marlowfoundation.org/news/spring-2014',
    surface: 'web',
    url: 'marlowfoundation.org/news/spring-2014',
    mentions: ['org.marlow-foundation', 'person.richard-vale', 'org.ridgeline'],
    factId: 'fact.vale-marlow-2013',
  },
  {
    id: 'w.conference-bio-2013',
    type: 'webPage',
    date: '2013-10-02',
    title: 'Oregon Philanthropy Forum 2013 — speakers',
    body: 'Panel three: stewardship and the small foundation. Speakers include A. Marlow (Chair, the Marlow Foundation) and R. Vale (Director, the Marlow Foundation; Managing Partner, Ridgeline Partners).',
    source: 'orphilanthropyforum.org/2013/speakers',
    surface: 'web',
    url: 'orphilanthropyforum.org/2013/speakers',
    mentions: ['person.alice-marlow', 'person.richard-vale', 'org.marlow-foundation'],
    factId: 'fact.vale-marlow-2013',
  },
  {
    id: 'w.grant-letter-2013',
    type: 'document',
    date: '2013-11-19',
    title: 'Marlow Foundation — grant award letter, Alberta Main Street',
    body: 'We are pleased to confirm an award of $40,000 toward the streetscape programme. Signed on behalf of the Board: R. Vale, Director.',
    source: 'albertamainst.org/funding/marlow-2013',
    surface: 'web',
    url: 'albertamainst.org/funding/marlow-2013',
    mentions: ['org.marlow-foundation', 'person.richard-vale', 'org.alberta-main-street'],
    amountCents: 4000000,
    factId: 'fact.vale-marlow-2013',
  },

  {
    id: 'w.charitywatch-marlow',
    type: 'record',
    date: '2015-02-27',
    title: 'Marlow Foundation — filing summary 2009–2014',
    body: 'Contributions received by year: 2009 $180,400 · 2010 $212,900 · 2011 $240,100 · 2012 $266,800 · 2013 $4,318,600 · 2014 $301,200. Disbursements track contributions within 5% in every year except 2013, where they match exactly.',
    source: 'nonprofit-filings.org/or/marlow-foundation',
    surface: 'archive',
    url: 'nonprofit-filings.org/or/marlow-foundation',
    mentions: ['org.marlow-foundation'],
    factId: 'fact.marlow-single-donor',
  },
  {
    id: 'w.local-piece-2014',
    type: 'webPage',
    date: '2014-01-30',
    title: 'A quiet year of record giving in Oregon',
    body: 'One Portland foundation reported contributions of more than four million dollars for 2013, an order of magnitude above its usual year. Its chair, Alice Marlow, said only that the gift was anonymous and that the Board had chosen to put it to work immediately.',
    source: 'pdxbusinessjournal.com/2014/record-giving',
    surface: 'web',
    url: 'pdxbusinessjournal.com/2014/record-giving',
    mentions: ['org.marlow-foundation', 'person.alice-marlow'],
    amountCents: 410000000,
    factId: 'fact.marlow-single-donor',
  },
  {
    id: 'w.marlow-faq',
    type: 'webPage',
    date: '2025-06-11',
    title: 'The Marlow Foundation — frequently asked questions',
    body: 'Do you accept anonymous gifts? Yes. Do you hold gifts over more than one financial year? As a rule the Board disburses within the year of receipt, so that the Foundation carries no endowment.',
    source: 'marlowfoundation.org/faq',
    surface: 'web',
    url: 'marlowfoundation.org/faq',
    mentions: ['org.marlow-foundation'],
    factId: 'fact.marlow-single-donor',
  },
  {
    id: 'w.registry-summary-2013',
    type: 'record',
    date: '2014-02-11',
    title: 'Oregon nonprofit registry — Marlow Foundation, 2013 summary page',
    body: 'Total contributions $4,318,600. Total disbursements $4,318,600. Net assets at year end: $0 change. Directors of record: A. Marlow, J. Reyes, R. Vale.',
    source: 'sos.oregon.gov/nonprofits/marlow-2013/summary',
    surface: 'archive',
    url: 'sos.oregon.gov/nonprofits/marlow-2013/summary',
    mentions: ['org.marlow-foundation', 'person.alice-marlow', 'person.joel-reyes', 'person.richard-vale'],
    factId: 'fact.marlow-single-donor',
  },

  // ------------------------------------------------------------- the anomaly

  {
    id: 'w.nova-mirror-docs',
    type: 'webPage',
    date: '2025-10-14',
    title: 'NOVA managed workstations — session mirroring',
    body: 'A managed workstation may be configured to mirror its session to a supervising peer. Mirroring is set at provisioning and is not surfaced in the case volume, so that a supervised session is indistinguishable from an unsupervised one to the person working it.',
    source: 'nova-systems.com/docs/managed/session-mirroring',
    surface: 'web',
    url: 'nova-systems.com/docs/managed/session-mirroring',
    mentions: [],
    fields: { applies_to: 'NOVA 3.x managed' },
    factId: 'fact.session-mirror',
  },
  {
    id: 'w.nova-changelog',
    type: 'webPage',
    date: '2024-08-19',
    title: 'NOVA 3.0 — release notes',
    body: 'Managed provisioning: session mirroring is now enabled by default on new managed volumes. Administrators who do not want it should clear the peer field at provisioning; it cannot be changed from the workstation afterwards.',
    source: 'nova-systems.com/releases/3-0',
    surface: 'web',
    url: 'nova-systems.com/releases/3-0',
    mentions: [],
    factId: 'fact.session-mirror',
  },
  {
    id: 'w.forum-smirror',
    type: 'forumPost',
    date: '2026-05-02',
    title: 'smirror on a single-seat licence?',
    body: 'Ran ps out of habit on a volume I was working and there is an smirror process pointed at 10.24.0.1. I am a single seat. Nobody supervises me. Support says it is standard and will not say standard for whom.',
    source: 'forensicsforum.net/thread/44127',
    surface: 'web',
    url: 'forensicsforum.net/thread/44127',
    mentions: [],
    factId: 'fact.session-mirror',
  },

  // ------------------------------------------------------------- side stories

  {
    id: 'w.pilot-sighting',
    type: 'forumPost',
    date: '2026-06-12',
    title: 'Re: Lost grey tabby — possible sighting',
    body: 'I think I heard a cat in the row of garages behind 22nd on Tuesday night and could not work out which one. Might be nothing. Worth knocking on a few doors.',
    source: 'nextdoor-alberta.com/thread/9011',
    surface: 'web',
    url: 'nextdoor-alberta.com/thread/9011',
    mentions: ['place.alberta', 'person.marguerite-hoy'],
    factId: 'fact.pilot-comes-home',
  },
  {
    id: 'w.pilot-found',
    type: 'forumPost',
    date: '2026-06-15',
    title: 'FOUND — Pilot is home',
    body: 'He was in the Cranstons\u2019 garage the whole time, since the Sunday, and they were away. Eight days, thin and furious and entirely fine. Thank you to everyone who looked.',
    source: 'nextdoor-alberta.com/thread/9026',
    surface: 'web',
    url: 'nextdoor-alberta.com/thread/9026',
    mentions: ['place.alberta', 'person.marguerite-hoy'],
    factId: 'fact.pilot-comes-home',
  },
  {
    id: 'w.pilot-thanks',
    type: 'classified',
    date: '2026-06-16',
    title: 'Withdrawn: lost grey tabby, NE 22nd and Alberta',
    body: 'Found, and thank you. Leaving this up one more day in case anybody still has a flyer on their gate.',
    source: 'pdxclassifieds.com/lost/pilot-grey-tabby-withdrawn',
    surface: 'web',
    url: 'pdxclassifieds.com/lost/pilot-grey-tabby-withdrawn',
    mentions: ['place.alberta', 'person.marguerite-hoy'],
    factId: 'fact.pilot-comes-home',
  },

  {
    id: 'w.studio-closing-notice',
    type: 'webPage',
    date: '2026-05-18',
    title: 'Ellery Ceramics — the studio is closing',
    body: 'After eleven years on Division the lease is up and I am not renewing it. Classes finish at the end of May. There will be one more firing.',
    source: 'ellery-ceramics.com/closing',
    surface: 'web',
    url: 'ellery-ceramics.com/closing',
    mentions: ['person.sofia-ellery', 'place.division-studio'],
    factId: 'fact.kiln-sold',
  },
  {
    id: 'w.last-firing',
    type: 'webPage',
    date: '2026-06-06',
    title: 'Ellery Ceramics — the last firing',
    body: 'Opened the kiln at six this morning with about thirty people outside on the pavement holding coffee. Everything survived except one of my own bowls, which felt about right. The kiln goes to a school in Gresham on Monday.',
    source: 'ellery-ceramics.com/last-firing',
    surface: 'web',
    url: 'ellery-ceramics.com/last-firing',
    mentions: ['person.sofia-ellery', 'place.division-studio'],
    factId: 'fact.kiln-sold',
  },
  {
    id: 'w.kiln-sold-update',
    type: 'classified',
    date: '2026-06-08',
    title: 'SOLD — Electric kiln, Skutt KM-1027',
    body: 'Gone to a high school ceramics programme, which is the outcome I wanted. The wheels are still available and I will take an offer.',
    source: 'pdxclassifieds.com/studio/skutt-km1027-sold',
    surface: 'web',
    url: 'pdxclassifieds.com/studio/skutt-km1027-sold',
    mentions: ['person.sofia-ellery'],
    factId: 'fact.kiln-sold',
  },

  // --------------------------------------------------- the ordinary, thickened

  {
    id: 'w.hill-club-results',
    type: 'webPage',
    date: '2026-06-03',
    title: 'Tuesday Night Hill Club — June standings',
    body: 'Six riders out on a wet evening. N. Okafor takes the Rocky Butte segment again. P. Brandt still not riding.',
    source: 'tuesdayhillclub.org/standings/june-2026',
    surface: 'web',
    url: 'tuesdayhillclub.org/standings/june-2026',
    mentions: ['org.hill-club', 'person.nadia-okafor', 'person.peter-brandt'],
    factId: 'fact.nadia-cycles',
  },
  {
    id: 'w.brandt-post',
    type: 'forumPost',
    date: '2026-04-21',
    title: 'Out for the season',
    body: 'Meniscus. Surgery on the 6th. I will be the one on the corner with the cowbell until September, so ride past slowly enough that I can shout at you.',
    source: 'tuesdayhillclub.org/board/thread/311',
    surface: 'web',
    url: 'tuesdayhillclub.org/board/thread/311',
    mentions: ['person.peter-brandt', 'org.hill-club'],
    factId: 'fact.brandt-knee',
  },
  {
    id: 'w.hill-club-roster-note',
    type: 'webPage',
    date: '2026-05-06',
    title: 'Tuesday Night Hill Club — ride leaders',
    body: 'Ride leaders through the summer: N. Okafor, S. Kwan, and whoever turns up first. P. Brandt is off the roster until his knee is signed off.',
    source: 'tuesdayhillclub.org/leaders',
    surface: 'web',
    url: 'tuesdayhillclub.org/leaders',
    mentions: ['org.hill-club', 'person.peter-brandt', 'person.nadia-okafor'],
    factId: 'fact.brandt-knee',
  },
  {
    id: 'w.fremont-signage',
    type: 'webPage',
    date: '2026-01-09',
    title: 'Fremont Street Parking — terms of use',
    body: 'Clause 11: recorded images are retained for eleven days and are released only to law enforcement on request. Clause 12: the operator accepts no liability for property left in a vehicle.',
    source: 'fremontparking.com/terms',
    surface: 'web',
    url: 'fremontparking.com/terms',
    mentions: ['place.fremont-lot'],
    factId: 'fact.fremont-loop',
  },
  {
    id: 'w.hollow-coast-interview',
    type: 'webPage',
    date: '2026-06-04',
    title: '"We are not breaking up, we are just tired": The Hollow Coast call it a year',
    body: 'The four-piece played what may be their last Portland show at the Doug Fir on 30 May. "Six years and a van," said their guitarist. "The van is the part that finally went."',
    source: 'pdxmusicweekly.com/hollow-coast-hiatus',
    surface: 'web',
    url: 'pdxmusicweekly.com/hollow-coast-hiatus',
    mentions: ['org.hollow-coast', 'place.doug-fir'],
    factId: 'fact.hollow-coast-hiatus',
  },
  {
    id: 'w.ridgeline-registry',
    type: 'record',
    date: '2011-10-03',
    title: 'Oregon business registry — Ridgeline Partners LLC',
    body: 'Registered 3 October 2011. Members of record at registration: R. Vale, T. Okonjo, H. Sandoval. Principal address: 1200 SW Morrison St, Portland.',
    source: 'sos.oregon.gov/business/ridgeline-partners',
    surface: 'archive',
    url: 'sos.oregon.gov/business/ridgeline-partners',
    mentions: ['org.ridgeline', 'person.richard-vale'],
    factId: 'fact.ridgeline-founded',
  },
  {
    id: 'w.alberta-rents-piece',
    type: 'webPage',
    date: '2026-03-12',
    title: 'Alberta Street rents up a fifth in two years',
    body: 'Ground-floor asking rents on the Alberta corridor have risen about twenty per cent since 2024. Three long-standing tenants have given notice this quarter.',
    source: 'pdxbusinessjournal.com/2026/alberta-rents',
    surface: 'web',
    url: 'pdxbusinessjournal.com/2026/alberta-rents',
    mentions: ['place.alberta', 'org.alberta-main-street'],
    factId: 'fact.alberta-rents',
  },
  {
    id: 'w.main-street-minutes',
    type: 'webPage',
    date: '2026-04-02',
    title: 'Alberta Main Street — board minutes, April',
    body: 'Item 4: rent pressure. The board notes three departures this quarter and agrees to write to the city. Item 5: block party permit lodged for 4 July, closure from 21st to 26th.',
    source: 'albertamainst.org/minutes/2026-04',
    surface: 'web',
    url: 'albertamainst.org/minutes/2026-04',
    mentions: ['org.alberta-main-street', 'place.alberta'],
    factId: 'fact.alberta-rents',
  },
  {
    id: 'w.city-permit',
    type: 'record',
    date: '2026-04-14',
    title: 'Portland street closure permit 2026-11482',
    body: 'Applicant: Alberta Main Street. NE Alberta St, NE 21st Ave to NE 26th Ave. 4 July 2026, 09:00 to 21:00. Approved.',
    source: 'portlandoregon.gov/permits/2026-11482',
    surface: 'archive',
    url: 'portlandoregon.gov/permits/2026-11482',
    mentions: ['org.alberta-main-street', 'place.alberta'],
    factId: 'fact.alberta-closure',
  },

  // ---------------------------------------------- and the rest of the internet

  {
    id: 'w.doug-fir-calendar',
    type: 'webPage',
    date: '2026-06-14',
    title: 'Doug Fir Lounge — June calendar',
    body: 'Fri 19: Weather Systems. Sat 20: Motel Motel. Wed 24: open decks. Thu 25: quiz, and yes it is still hard.',
    source: 'dougfirlounge.com/calendar/june',
    surface: 'web',
    url: 'dougfirlounge.com/calendar/june',
    mentions: ['place.doug-fir'],
  },
  {
    id: 'w.library-hours',
    type: 'webPage',
    date: '2026-05-30',
    title: 'Multnomah County Library — Alberta branch hours',
    body: 'Mon to Thu 10:00 to 20:00. Fri and Sat 10:00 to 18:00. Sun 12:00 to 17:00. The meeting room is bookable two weeks ahead.',
    source: 'multcolib.org/alberta/hours',
    surface: 'web',
    url: 'multcolib.org/alberta/hours',
    mentions: ['place.alberta'],
  },
  {
    id: 'w.school-calendar',
    type: 'webPage',
    date: '2026-05-22',
    title: 'Vernon Elementary — end of year',
    body: 'Last day of school 18 June. Field day 16 June, parents welcome. Please return library books before the 12th.',
    source: 'vernon-elementary.pps.net/news/end-of-year',
    surface: 'web',
    url: 'vernon-elementary.pps.net/news/end-of-year',
    mentions: ['org.vernon-elementary'],
  },
  {
    id: 'w.pta-raffle',
    type: 'webPage',
    date: '2026-04-28',
    title: 'Vernon PTA — spring raffle results',
    body: 'We raised $4,180 for the library fund. Thank you to the forty-one families who sold tickets and to the bakery on 15th for the cakes.',
    source: 'vernon-elementary.pps.net/pta/raffle-2026',
    surface: 'web',
    url: 'vernon-elementary.pps.net/pta/raffle-2026',
    mentions: ['org.vernon-elementary'],
  },
  {
    id: 'w.bike-shop',
    type: 'webPage',
    date: '2026-06-01',
    title: 'North Portland Cyclery — summer service slots',
    body: 'We are booking two weeks out. Drop-offs before 10:00 go on the same-day board. We do not true carbon wheels, sorry.',
    source: 'npcyclery.com/service',
    surface: 'web',
    url: 'npcyclery.com/service',
    mentions: [],
  },
  {
    id: 'w.cafe-hiring',
    type: 'classified',
    date: '2026-06-03',
    title: 'Barista wanted — Alberta',
    body: 'Four shifts, one of them a weekend. Experience nice, attitude essential. We close at three and we mean it.',
    source: 'pdxclassifieds.com/jobs/barista-alberta',
    surface: 'web',
    url: 'pdxclassifieds.com/jobs/barista-alberta',
    mentions: ['place.alberta'],
  },
  {
    id: 'w.moving-sale',
    type: 'classified',
    date: '2026-06-07',
    title: 'Moving sale — NE 24th, Saturday',
    body: 'Everything that will not fit in the van. Bookshelves, a good chair, an alarming quantity of jam jars. Cash, early birds welcome, no holds.',
    source: 'pdxclassifieds.com/sales/ne-24th-june',
    surface: 'web',
    url: 'pdxclassifieds.com/sales/ne-24th-june',
    mentions: ['place.alberta'],
  },
  {
    id: 'w.sofa-free',
    type: 'classified',
    date: '2026-06-10',
    title: 'Free sofa, you collect',
    body: 'Green, two-seater, one cat-related incident in 2021 which you cannot see from the front. On the porch until it rains.',
    source: 'pdxclassifieds.com/free/green-sofa',
    surface: 'web',
    url: 'pdxclassifieds.com/free/green-sofa',
    mentions: [],
  },
  {
    id: 'w.transit-alert',
    type: 'webPage',
    date: '2026-06-09',
    title: 'TriMet — line 72 detour',
    body: 'Line 72 is on detour between Killingsworth and Prescott until 20 June for paving. Use the temporary stop at NE 27th.',
    source: 'trimet.org/alerts/72-june',
    surface: 'web',
    url: 'trimet.org/alerts/72-june',
    mentions: [],
  },
  {
    id: 'w.farmers-market',
    type: 'webPage',
    date: '2026-06-05',
    title: 'Woodlawn farmers market — June vendors',
    body: 'Strawberries from the 12th, probably. Two new bread stalls. The knife sharpener is back on alternate weeks.',
    source: 'woodlawnmarket.org/june',
    surface: 'web',
    url: 'woodlawnmarket.org/june',
    mentions: [],
  },
  {
    id: 'w.dog-park-consult',
    type: 'webPage',
    date: '2026-05-19',
    title: 'Parks consultation — off-leash hours at Alberta Park',
    body: 'The consultation closes 30 June. Two hundred and six responses so far, of which a hundred and ninety are about the same corner of the field.',
    source: 'portlandoregon.gov/parks/alberta-offleash',
    surface: 'web',
    url: 'portlandoregon.gov/parks/alberta-offleash',
    mentions: ['place.alberta'],
  },
  {
    id: 'w.roofing-quote-thread',
    type: 'forumPost',
    date: '2026-05-28',
    title: 'Anybody had a roof quote lately?',
    body: 'Three quotes, all within four hundred dollars of each other, which either means the market is honest or they drink together. Posting the numbers in case it helps somebody.',
    source: 'nextdoor-alberta.com/thread/8877',
    surface: 'web',
    url: 'nextdoor-alberta.com/thread/8877',
    mentions: ['place.alberta'],
  },
  {
    id: 'w.power-outage',
    type: 'webPage',
    date: '2026-06-09',
    title: 'PGE — outage summary, 9 June',
    body: 'A fault at 20:44 affected 1,140 customers in NE Portland. Power was restored to all customers by 21:10. Cause: equipment failure.',
    source: 'portlandgeneral.com/outages/2026-06-09',
    surface: 'web',
    url: 'portlandgeneral.com/outages/2026-06-09',
    mentions: [],
  },
  {
    id: 'w.cascade-mobile-plans',
    type: 'webPage',
    date: '2026-02-02',
    title: 'Cascade Mobile — plans',
    body: 'Unlimited talk and text on every plan. Data from 5 GB. Family plans add a line for nine dollars. No contract, and no charge to leave.',
    source: 'cascademobile.com/plans',
    surface: 'web',
    url: 'cascademobile.com/plans',
    mentions: ['org.cascade-mobile'],
  },
  {
    id: 'w.cascade-outage-note',
    type: 'webPage',
    date: '2026-06-09',
    title: 'Cascade Mobile — network status',
    body: 'All systems normal. Last incident: 2 June, degraded data in the Portland metro for 40 minutes.',
    source: 'cascademobile.com/status',
    surface: 'web',
    url: 'cascademobile.com/status',
    mentions: ['org.cascade-mobile'],
  },
  {
    id: 'w.ridgeline-note-clients',
    type: 'webPage',
    date: '2026-01-15',
    title: 'Ridgeline Partners — a note to clients',
    body: 'Our quarterly letters move to a secure portal from February. If you would rather keep receiving paper, tell us and we will keep sending it.',
    source: 'ridgelinepartners.com/notes/portal',
    surface: 'web',
    url: 'ridgelinepartners.com/notes/portal',
    mentions: ['org.ridgeline'],
  },
  {
    id: 'w.kgw-traffic',
    type: 'webPage',
    date: '2026-06-16',
    title: 'KGW — traffic, Tuesday morning',
    body: 'A stall on the Banfield eastbound is clearing. The Fremont Bridge northbound closures resume tonight at ten.',
    source: 'kgw-portland.com/traffic/2026-06-16',
    surface: 'web',
    url: 'kgw-portland.com/traffic/2026-06-16',
    mentions: ['org.kgw'],
  },
  {
    id: 'w.kgw-corrections',
    type: 'webPage',
    date: '2026-06-15',
    title: 'KGW — corrections',
    body: '12 June: a report on the housing bond gave the shortfall as $4.1m. The correct figure is $1.4m. We regret the error.',
    source: 'kgw-portland.com/corrections',
    surface: 'web',
    url: 'kgw-portland.com/corrections',
    mentions: ['org.kgw'],
  },
  {
    id: 'w.storage-rates',
    type: 'webPage',
    date: '2026-03-21',
    title: 'Rose City Self Storage — unit sizes and rates',
    body: '5x5 from $46. 10x10 from $118. First month half price on a six-month term. Units are not climate controlled.',
    source: 'rosecitystorage.com/rates',
    surface: 'web',
    url: 'rosecitystorage.com/rates',
    mentions: [],
  },
  {
    id: 'w.locksmith',
    type: 'classified',
    date: '2026-05-24',
    title: 'Locksmith — 24 hour, NE Portland',
    body: 'Lockouts, rekeying, safes. We do not open a door without identification and proof of address, and please do not ask.',
    source: 'pdxclassifieds.com/services/ne-locksmith',
    surface: 'web',
    url: 'pdxclassifieds.com/services/ne-locksmith',
    mentions: [],
  },
]
