import type { z } from 'zod'
import type { WorldArtifactSchema } from '@/engine/world/schema'

type ArtifactInput = z.input<typeof WorldArtifactSchema>

/**
 * The traces. One fact, many surfaces.
 *
 * Most of what is here carries no fact at all, and that is the point: it is the rest of the
 * internet — a band on hiatus, a cycling club, a car park's opening hours. A world where every
 * page is about the case stops being a world.
 *
 * Every page on the web needs an address, and no two documents may share one. The case's own
 * pages are projected into this same graph by `content/index.ts`, so nothing here may sit at an
 * address a case already authored.
 */
export const artifacts: ArtifactInput[] = [
  // --------------------------------------------------------------- the case
  {
    id: 'w.registry-marlow-2013',
    type: 'record',
    date: '2014-02-11',
    title: 'Marlow Foundation — 2013 annual filing (scanned)',
    body: 'Directors of record for the year ended 31 December 2013: A. Marlow (Chair), J. Reyes (Treasurer), R. Vale (Director). Resignation of R. Vale recorded 14 March 2014.',
    source: 'Oregon Secretary of State — Corporation Division',
    surface: 'archive',
    url: 'sos.oregon.gov/nonprofits/marlow-2013',
    mentions: ['org.marlow-foundation', 'person.richard-vale', 'person.joel-reyes'],
    fields: { filed: '11 February 2014', pages: '6' },
    factId: 'fact.vale-marlow-2013',
  },
  {
    id: 'w.marlow-report-2013',
    type: 'webPage',
    date: '2014-05-02',
    title: 'The Marlow Foundation — 2013 in review',
    body: 'Our thanks to the board for a year of growth: Alice Marlow, Joel Reyes and Richard Vale. The Foundation disbursed grants across housing and arts programmes in five counties.',
    source: 'marlowfoundation.org/reports/2013',
    surface: 'web',
    url: 'marlowfoundation.org/reports/2013',
    mentions: ['org.marlow-foundation', 'person.richard-vale', 'person.joel-reyes'],
    factId: 'fact.vale-marlow-2013',
  },
  {
    id: 'w.ridgeline-about',
    type: 'webPage',
    date: '2025-11-04',
    title: 'Ridgeline Partners — About',
    body: 'Ridgeline was founded in Portland in 2011 by Richard Vale and two partners. We manage capital for families and foundations in the Pacific Northwest.',
    source: 'ridgelinepartners.com/about',
    surface: 'web',
    url: 'ridgelinepartners.com/about',
    mentions: ['org.ridgeline', 'person.richard-vale'],
    factId: 'fact.ridgeline-founded',
  },
  {
    id: 'w.business-journal-2011',
    type: 'webPage',
    date: '2011-09-19',
    title: 'Three leave Cascadia Capital to start Ridgeline',
    body: 'Richard Vale, formerly of Cascadia Capital, has registered a new advisory firm in Portland with two colleagues. Ridgeline Partners begins trading in October.',
    source: 'pdxbusinessjournal.com/2011/ridgeline-launch',
    surface: 'web',
    url: 'pdxbusinessjournal.com/2011/ridgeline-launch',
    mentions: ['person.richard-vale', 'org.ridgeline'],
    factId: 'fact.ridgeline-founded',
  },

  // ------------------------------------------------------------- the ordinary
  {
    id: 'w.fremont-faq',
    type: 'webPage',
    date: '2026-03-02',
    title: 'Fremont Street Parking — Frequently asked questions',
    body: 'How long do you keep camera footage? The barrier cameras write to an eleven-day loop. After that it is overwritten and we cannot recover it. Please contact us promptly.',
    source: 'fremontparking.com/faq',
    surface: 'web',
    url: 'fremontparking.com/faq',
    mentions: ['place.fremont-lot'],
    factId: 'fact.fremont-loop',
  },
  {
    id: 'w.alberta-thread-8812',
    type: 'forumPost',
    date: '2026-04-18',
    title: 'Anyone got footage from the Fremont lot?',
    body: 'Somebody clipped my mirror on level 2. Called the office and they said eleven days and then it is gone. Eleven days! Anyway if you saw a silver estate, you know where I am.',
    source: 'nextdoor-alberta.com/thread/8812',
    surface: 'web',
    url: 'nextdoor-alberta.com/thread/8812',
    mentions: ['place.fremont-lot'],
    factId: 'fact.fremont-loop',
  },
  {
    id: 'w.strava-club',
    type: 'webPage',
    date: '2026-05-05',
    title: 'Tuesday Night Hill Club — members',
    body: 'Rides leave from the east end of the Tilikum at 18:30, all weathers. Current members include N. Okafor, P. Brandt, S. Ellery and eleven others.',
    source: 'tuesdayhillclub.org/members',
    surface: 'web',
    url: 'tuesdayhillclub.org/members',
    mentions: ['person.nadia-okafor'],
    factId: 'fact.nadia-cycles',
  },
  {
    id: 'w.bike-classified',
    type: 'classified',
    date: '2026-05-21',
    title: 'Steel road bike, 54cm — $640',
    body: 'Selling my winter bike, 54cm steel frame, recently serviced. Collection in Sellwood, evenings. I ride Tuesdays so message rather than call.',
    source: 'pdxclassifieds.com/bikes/54cm-steel',
    surface: 'web',
    url: 'pdxclassifieds.com/bikes/54cm-steel',
    mentions: ['person.nadia-okafor'],
    factId: 'fact.nadia-cycles',
  },
  {
    id: 'w.dougfir-listing',
    type: 'webPage',
    date: '2026-05-30',
    title: 'Doug Fir Lounge — 30 May: The Hollow Coast',
    body: 'The Hollow Coast, with support from Weather Systems. Doors 20:00. This is being billed as their last show for a while.',
    source: 'dougfirlounge.com/shows/2026-05-30',
    surface: 'web',
    url: 'dougfirlounge.com/shows/2026-05-30',
    mentions: ['org.hollow-coast'],
    factId: 'fact.hollow-coast-hiatus',
  },
  {
    id: 'w.hollow-coast-press',
    type: 'webPage',
    date: '2026-06-01',
    title: 'The Hollow Coast — press',
    body: 'After six years we are taking the rest of the year off. Thank you to everyone who came to the Doug Fir. The van is for sale and so is the second-best amp.',
    source: 'pdxbands.com/the-hollow-coast/press',
    surface: 'web',
    url: 'pdxbands.com/the-hollow-coast/press',
    mentions: ['org.hollow-coast'],
    factId: 'fact.hollow-coast-hiatus',
  },
  {
    id: 'w.vernon-staff',
    type: 'webPage',
    date: '2025-09-08',
    title: 'Vernon Elementary — Fourth grade',
    body: 'Room 12 — Ms C. Mercer. Room 14 — Mr D. Achterberg. Fourth grade families, please use the Alberta Street entrance after 08:15.',
    source: 'vernon-elementary.pps.net/staff/grade-4',
    surface: 'web',
    url: 'vernon-elementary.pps.net/staff/grade-4',
    mentions: ['person.claire-mercer'],
    factId: 'fact.claire-teaches',
  },
  {
    id: 'w.vernon-newsletter',
    type: 'webPage',
    date: '2026-05-15',
    title: 'Vernon Elementary — May newsletter',
    body: 'Thank you to Ms Mercer for organising the fourth-grade trip to the Columbia Gorge, and to the eleven parents who drove.',
    source: 'vernon-elementary.pps.net/news/may-2026',
    surface: 'web',
    url: 'vernon-elementary.pps.net/news/may-2026',
    mentions: ['person.claire-mercer'],
    factId: 'fact.claire-teaches',
  },

  // A sincerely wrong document, and the thing that catches it. A lie the player cannot catch is
  // not a lie — it is the world simply telling them something untrue.
  {
    id: 'w.neighbour-sighting',
    type: 'forumPost',
    date: '2026-06-12',
    title: 'Re: missing man on Alberta',
    body: 'I am fairly sure I saw him on the Wednesday morning by the coffee place, so whatever the family says he was still around on the 10th.',
    source: 'nextdoor-alberta.com/thread/9004',
    surface: 'web',
    url: 'nextdoor-alberta.com/thread/9004',
    mentions: ['person.daniel-mercer', 'place.alberta'],
    reliability: 'mistaken',
    disputedClaim: 'he was still around on the 10th',
    contradicts: ['w.coffee-closure'],
  },
  {
    id: 'w.coffee-closure',
    type: 'webPage',
    date: '2026-06-08',
    title: 'Proud Mary Alberta — closed 10–14 June',
    body: 'We are closed Wednesday the 10th through Sunday the 14th for a floor replacement. The Division shop is open as usual. Sorry for the inconvenience.',
    source: 'proudmarycafe.com/notices/june-closure',
    surface: 'web',
    url: 'proudmarycafe.com/notices/june-closure',
    mentions: ['place.alberta'],
  },

  // -------------------------------------------------------- ordinary, no fact
  {
    id: 'w.alberta-block-party',
    type: 'webPage',
    date: '2026-06-02',
    title: 'Alberta Street block party — 4 July',
    body: 'Volunteers still needed for setup, the lemonade table and the 17:00 teardown. Street closure runs from 21st to 26th.',
    source: 'albertamainst.org/block-party-2026',
    surface: 'web',
    url: 'albertamainst.org/block-party-2026',
    mentions: ['place.alberta'],
  },
  {
    id: 'w.lost-cat',
    type: 'classified',
    date: '2026-06-11',
    title: 'Lost: grey tabby, NE 22nd and Alberta',
    body: 'Answers to Pilot, or does not. Chipped. He has been out four nights and I am not sleeping. Any sighting, any time.',
    source: 'pdxclassifieds.com/lost/pilot-grey-tabby',
    surface: 'web',
    url: 'pdxclassifieds.com/lost/pilot-grey-tabby',
    mentions: ['place.alberta'],
  },
  {
    id: 'w.kiln-sale',
    type: 'classified',
    date: '2026-05-27',
    title: 'Electric kiln, Skutt KM-1027 — $1,900',
    body: 'Studio closing after eleven years. Kiln, two wheels, and about forty bats. Buyer collects, and you will need three people and a van.',
    source: 'pdxclassifieds.com/studio/skutt-km1027',
    surface: 'web',
    url: 'pdxclassifieds.com/studio/skutt-km1027',
    mentions: [],
  },
  {
    id: 'w.bridge-closure',
    type: 'webPage',
    date: '2026-06-05',
    title: 'Fremont Bridge — overnight lane closures',
    body: 'Northbound lanes close 22:00 to 05:00 from 8 June to 19 June for deck inspection. Use the Broadway Bridge.',
    source: 'portlandoregon.gov/transport/fremont-june',
    surface: 'web',
    url: 'portlandoregon.gov/transport/fremont-june',
    mentions: [],
  },
  {
    id: 'w.kgw-weather',
    type: 'webPage',
    date: '2026-06-09',
    title: 'Portland forecast — Tuesday 9 June',
    body: 'Cloud clearing after 21:00, low of 11. Dry through midweek. Rain returns Thursday evening.',
    source: 'kgw-portland.com/weather/2026-06-09',
    surface: 'web',
    url: 'kgw-portland.com/weather/2026-06-09',
    mentions: ['org.kgw'],
  },
  {
    id: 'w.whitfield-byline',
    type: 'webPage',
    date: '2026-06-14',
    title: 'Amara Whitfield — recent stories',
    body: 'Housing bond shortfall · County shelter contract · School board resignation · Family appeals for information on missing Portland man.',
    source: 'kgw-portland.com/staff/amara-whitfield',
    surface: 'web',
    url: 'kgw-portland.com/staff/amara-whitfield',
    mentions: ['person.amara-whitfield', 'org.kgw'],
  },
  {
    id: 'w.ridgeline-hiring',
    type: 'webPage',
    date: '2026-04-30',
    title: 'Ridgeline Partners — Careers',
    body: 'We are hiring an operations associate. Portland office, four days on site. No agencies.',
    source: 'ridgelinepartners.com/careers',
    surface: 'web',
    url: 'ridgelinepartners.com/careers',
    mentions: ['org.ridgeline'],
  },
  {
    id: 'w.marlow-grants-2025',
    type: 'webPage',
    date: '2026-01-22',
    title: 'The Marlow Foundation — 2025 grants',
    body: 'Forty-one grants across housing, arts and early education. The Foundation does not accept unsolicited applications.',
    source: 'marlowfoundation.org/grants/2025',
    surface: 'web',
    url: 'marlowfoundation.org/grants/2025',
    mentions: ['org.marlow-foundation'],
  },
  {
    id: 'w.storage-unit',
    type: 'webPage',
    date: '2026-02-14',
    title: 'Rose City Self Storage — access hours',
    body: 'Gate access 06:00 to 22:00 daily. Units are accessed by a four-digit code set by the tenant. Codes are not held by staff.',
    source: 'rosecitystorage.com/access',
    surface: 'web',
    url: 'rosecitystorage.com/access',
    mentions: [],
  },
  {
    id: 'w.cascade-mobile-coverage',
    type: 'webPage',
    date: '2026-03-19',
    title: 'Cascade Mobile — coverage and records',
    body: 'Call and message metadata is retained for 90 days on your account and for longer under our carrier obligations. Handsets hold the last 30 days.',
    source: 'cascademobile.com/support/records',
    surface: 'web',
    url: 'cascademobile.com/support/records',
    mentions: ['device.nova-m12'],
  },
]
